### ISSUE TITLE
Get Songs By ID

### ISSUE THREAD

**Issue by fredroo** [simivar/Genius-PHP#25]
How i can get all lyrics from GENIUS with your project by song ID

**Comment by simivar** [comment]
Right now the library supports only official API from docs.genius.com. Unfortunately getting lyrics is not supported due legal reasons as stated [in this forum post](https://genius.com/discussions/277279-Get-the-lyrics-of-a-song).

**Comment by fredroo** [comment]
ok thanks @simivar
