### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by CharlieMillscn** [simivar/Genius-PHP#7]
```
Using version ^1.0 for simivar/genius-php
Using version ^1.8 for php-http/message
Using version ^2.0 for php-http/guzzle6-adapter
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install simivar/genius-php 1.0.1
    - Installation request for simivar/genius-php ^1.0 -> satisfiable by simivar/genius-php[1.0.0, 1.0.1].
    - Conclusion: don't install php-http/guzzle6-adapter v2.0.1
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, v2.0.0].
    - Can only install one of: php-http/httplug[v1.0.0, 2.1.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.0.0].
    - simivar/genius-php 1.0.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - Conclusion: don't install php-http/guzzle6-adapter v2.0.0|don't install php-http/httplug v1.1.0
    - Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].

Installation failed, deleting ./composer.json.
```

**Comment by simivar** [comment]
I just published version 2.0.0 in #8 and #9. It should now work as expected. 

**Beware!** Please check [CHANGELOG.md](https://github.com/simivar/Genius-PHP/blob/master/CHANGELOG.md) for list of all changes. Some method singatures have changed!

**Comment by CharlieMillscn** [comment]
Yes!It works!Thank you!

**Comment by CharlieMillscn** [comment]
when i use your example usage in my website,it occurred a fatal error,i don't know what to do
```
<?php
require_once('vendor/autoload.php');

$geniusphp = new \Genius\Genius('TfBRgnzAKHV8GqBjOy1ec'); // my genius CLIENT ACCESS TOKEN

// let's search for the most popular song on Genius for Kendrick Lamar
$search = $geniusphp->search->get('Kendrick Lamar')->response->hits[0]->result->id;

// and get everything about that song
$song = $geniusphp->songs->get( $search );
```
`Fatal error: Uncaught TypeError: Argument 1 passed to Genius\Genius::__construct() must be an instance of Http\Message\Authentication, string given, called in D:\phpstudy_pro\WWW\genius\index.php on line 4 and defined in D:\phpstudy_pro\WWW\genius\vendor\simivar\genius-php\src\Genius\Genius.php:47 Stack trace: #0 D:\phpstudy_pro\WWW\genius\index.php(4): Genius\Genius->__construct('TfBRgnzAKHV8GqB...') #1 {main} thrown in D:\phpstudy_pro\WWW\genius\vendor\simivar\genius-php\src\Genius\Genius.php on line 47`

**Comment by CharlieMillscn** [comment]
when i use your example usage in my website,it occurred a fatal error,i don't know what to do
```
<?php
require_once('vendor/autoload.php');

$geniusphp = new \Genius\Genius('TfBRgnzAKHV8GqBjOy1ec'); // my genius CLIENT ACCESS TOKEN

// let's search for the most popular song on Genius for Kendrick Lamar
$search = $geniusphp->search->get('Kendrick Lamar')->response->hits[0]->result->id;

// and get everything about that song
$song = $geniusphp->songs->get( $search );
```
`Fatal error: Uncaught TypeError: Argument 1 passed to Genius\Genius::__construct() must be an instance of Http\Message\Authentication, string given, called in D:\phpstudy_pro\WWW\genius\index.php on line 4 and defined in D:\phpstudy_pro\WWW\genius\vendor\simivar\genius-php\src\Genius\Genius.php:47 Stack trace: #0 D:\phpstudy_pro\WWW\genius\index.php(4): Genius\Genius->__construct('TfBRgnzAKHV8GqB...') #1 {main} thrown in D:\phpstudy_pro\WWW\genius\vendor\simivar\genius-php\src\Genius\Genius.php on line 47`

**Comment by simivar** [comment]
You are still using example from version 0.1.x that is abandoned while using 2.x version of library. In current [README.md](https://github.com/simivar/Genius-PHP/blob/master/README.md) you will find more up-to-date example but with oAuth2. 

If you want just to use `Bearer` as it seems instead of creating `\Genius\Authentication\OAuth2` object create `Http\Message\Authentication\Bearer` object and pass it to `\Genius\Genius` constructor.

**Beware!** If you use `Bearer` instead of `oAuth2` you can't access endpoints that require some scope like upvoting an annotation etc. You should get proper `Exception` with message when it happens. You can find out more in [Genius API Docs](https://docs.genius.com/).

For example:
```php
require_once('vendor/autoload.php');

$authentication = new \Http\Message\Authentication\Bearer('YOUR_ACCESS_TOKEN');
$genius = new \Genius\Genius($authentication);
$searchSong = $genius->getSearchResource()->get('Kendrick Lamar');
```

**Comment by simivar** [comment]
I am closing the issue as the main problem is fixed. If you have still any questions feel free to ask them here.

If you find any other issue with library feel to free to open another issue. 

Have a good day!
